/*
 * generated by Xtext 2.11.0
 */
package org.moflon.gt.mosl.controlflow.language.ide


/**
 * Use this class to register ide components.
 */
class MOSLControlFlowIdeModule extends AbstractMOSLControlFlowIdeModule {
}
